# Generated by Django 5.2.5 on 2025-08-27 03:31

import django.db.models.deletion
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono', max_length=15, null=True)),
                ('documento', models.CharField(blank=True, help_text='Número de documento de identidad', max_length=20, null=True)),
                ('tipo_usuario', models.CharField(choices=[('instructor', 'Instructor'), ('estudiante', 'Estudiante'), ('admin', 'Administrador')], default='instructor', help_text='Tipo de usuario en el sistema', max_length=20)),
                ('tipo_naturaleza', models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='natural', help_text='Tipo de naturaleza jurídica', max_length=20)),
                ('biografia', models.TextField(blank=True, help_text='Biografía del usuario', max_length=500, null=True)),
                ('foto', models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to=usuarios.models.upload_profile_image)),
                ('linkedin', models.URLField(blank=True, help_text='Perfil de LinkedIn', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Perfil de Twitter', null=True)),
                ('github', models.URLField(blank=True, help_text='Perfil de GitHub', null=True)),
                ('sitio_web', models.URLField(blank=True, help_text='Sitio web personal', null=True)),
                ('esta_verificado', models.BooleanField(default=False, help_text='Indica si el perfil está verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
